name: Docker Image CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
        with:
          username: ondrejsika
          password: ${{ secrets.DOCKERHUB_ONDREJSIKA_PASSWORD }}
    - uses: docker/login-action@v1
        with:
          username: sikalabs
          password: ${{ secrets.DOCKERHUB_SIKALABS_PASSWORD }}
    - name: Build the Docker image
      run: make all
